name: Ansible Galaxy Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Ansible Publish
    runs-on: ubuntu-latest
    steps:
      - uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY_TOKEN }}
          api_server: https://galaxy.ansible.com
          src_path: .
